# Generated by Django 4.0.6 on 2022-07-26 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_login_remove_male_girls_remove_user_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='user_name',
            new_name='username',
        ),
    ]
